
# opaflib/parsetab_pdf.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '4$\xa0"\x0c\'W\xac\xbb\x08y\xcet)S\''
    
_lr_action_items = {'DOUBLE_GREATER_THAN_SIGN':([15,17,18,20,21,22,23,24,25,26,30,33,37,39,41,],[-5,-7,-17,-8,-12,-10,-14,-11,-9,-6,-13,39,-2,-15,-16,]),'XREF':([2,3,4,5,8,10,11,13,28,34,38,],[-30,9,-27,-30,-28,-29,-26,-24,-25,-20,-21,]),'OBJ':([2,3,4,5,8,10,11,13,28,34,38,],[-30,7,-27,-30,-28,-29,-26,-24,-25,-20,-21,]),'NAME':([7,14,15,17,18,20,21,22,23,24,25,26,29,30,33,37,39,40,41,],[15,15,-5,-7,-17,-8,-12,-10,-14,-11,-9,-6,15,-13,40,-2,-15,15,-16,]),'ENDOBJ':([15,16,17,19,20,21,22,23,24,25,26,32,37,39,],[-5,-13,-7,34,-8,-12,-10,-14,-11,-9,-6,38,-2,-15,]),'HEXSTRING':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[17,17,-5,-7,-8,-12,-10,-14,-11,-9,-6,17,-13,-2,-15,17,]),'DOUBLE_LESS_THAN_SIGN':([7,14,15,17,20,21,22,23,24,25,26,27,29,30,37,39,40,],[18,18,-5,-7,-8,-12,-10,-14,-11,-9,-6,18,18,-13,-2,-15,18,]),'NUMBER':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[20,20,-5,-7,-8,-12,-10,-14,-11,-9,-6,20,-13,-2,-15,20,]),'LEFT_SQUARE_BRACKET':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[14,14,-5,-7,-8,-12,-10,-14,-11,-9,-6,14,-13,-2,-15,14,]),'HEADER':([0,],[2,]),'STARTXREF':([6,10,35,38,39,],[12,-23,-22,-21,-15,]),'R':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[21,21,-5,-7,-8,-12,-10,-14,-11,-9,-6,21,-13,-2,-15,21,]),'STREAM_DATA':([16,39,],[32,-15,]),'EOF':([12,],[28,]),'FALSE':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[22,22,-5,-7,-8,-12,-10,-14,-11,-9,-6,22,-13,-2,-15,22,]),'STRING':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[26,26,-5,-7,-8,-12,-10,-14,-11,-9,-6,26,-13,-2,-15,26,]),'NULL':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[24,24,-5,-7,-8,-12,-10,-14,-11,-9,-6,24,-13,-2,-15,24,]),'TRUE':([7,14,15,17,20,21,22,23,24,25,26,29,30,37,39,40,],[25,25,-5,-7,-8,-12,-10,-14,-11,-9,-6,25,-13,-2,-15,25,]),'RIGHT_SQUARE_BRACKET':([14,15,17,20,21,22,23,24,25,26,29,30,31,36,37,39,],[-4,-5,-7,-8,-12,-10,-14,-11,-9,-6,-4,-13,37,-3,-2,-15,]),'TRAILER':([9,],[27,]),'$end':([1,4,5,11,13,28,],[0,-27,-1,-26,-24,-25,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([2,5,],[3,3,]),'xref':([3,],[6,]),'dictionary':([7,14,27,29,40,],[16,30,35,30,30,]),'pdf_end':([6,],[13,]),'object':([7,14,29,40,],[19,29,29,41,]),'pdf_update':([2,5,],[4,11,]),'dictionary_entry_list':([18,],[33,]),'indirect_object':([3,],[8,]),'object_list':([14,29,],[31,36,]),'indirect_object_stream':([3,],[10,]),'pdf':([0,],[1,]),'pdf_update_list':([2,],[5,]),'array':([7,14,29,40,],[23,23,23,23,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pdf","S'",1,None,None,None),
  ('pdf -> HEADER pdf_update_list','pdf',2,'p_pdf','opaflib/parser.py',24),
  ('array -> LEFT_SQUARE_BRACKET object_list RIGHT_SQUARE_BRACKET','array',3,'p_array','opaflib/parser.py',36),
  ('object_list -> object object_list','object_list',2,'p_object_list','opaflib/parser.py',40),
  ('object_list -> <empty>','object_list',0,'p_object_list_empty','opaflib/parser.py',44),
  ('object -> NAME','object',1,'p_object_name','opaflib/parser.py',49),
  ('object -> STRING','object',1,'p_object_string','opaflib/parser.py',53),
  ('object -> HEXSTRING','object',1,'p_object_hexstring','opaflib/parser.py',57),
  ('object -> NUMBER','object',1,'p_object_number','opaflib/parser.py',61),
  ('object -> TRUE','object',1,'p_object_true','opaflib/parser.py',65),
  ('object -> FALSE','object',1,'p_object_false','opaflib/parser.py',69),
  ('object -> NULL','object',1,'p_object_null','opaflib/parser.py',73),
  ('object -> R','object',1,'p_object_ref','opaflib/parser.py',77),
  ('object -> dictionary','object',1,'p_object_dictionary','opaflib/parser.py',82),
  ('object -> array','object',1,'p_object_array','opaflib/parser.py',86),
  ('dictionary -> DOUBLE_LESS_THAN_SIGN dictionary_entry_list DOUBLE_GREATER_THAN_SIGN','dictionary',3,'p_dictionary','opaflib/parser.py',96),
  ('dictionary_entry_list -> dictionary_entry_list NAME object','dictionary_entry_list',3,'p_dictionary_entry_list','opaflib/parser.py',100),
  ('dictionary_entry_list -> <empty>','dictionary_entry_list',0,'p_dictionary_entry_list','opaflib/parser.py',101),
  ('indirect -> indirect_object_stream','indirect',1,'p_indirect','opaflib/parser.py',119),
  ('indirect -> indirect_object','indirect',1,'p_indirect','opaflib/parser.py',120),
  ('indirect_object -> OBJ object ENDOBJ','indirect_object',3,'p_indirect_object','opaflib/parser.py',125),
  ('indirect_object_stream -> OBJ dictionary STREAM_DATA ENDOBJ','indirect_object_stream',4,'p_indirect_object_stream','opaflib/parser.py',129),
  ('xref -> XREF TRAILER dictionary','xref',3,'p_xref_common','opaflib/parser.py',146),
  ('xref -> indirect_object_stream','xref',1,'p_xref_stream','opaflib/parser.py',152),
  ('pdf_update -> body xref pdf_end','pdf_update',3,'p_pdf_update','opaflib/parser.py',157),
  ('pdf_end -> STARTXREF EOF','pdf_end',2,'p_pdf_end','opaflib/parser.py',168),
  ('pdf_update_list -> pdf_update_list pdf_update','pdf_update_list',2,'p_pdf_update_list','opaflib/parser.py',172),
  ('pdf_update_list -> pdf_update','pdf_update_list',1,'p_pdf_update_list_one','opaflib/parser.py',178),
  ('body -> body indirect_object','body',2,'p_body_object','opaflib/parser.py',183),
  ('body -> body indirect_object_stream','body',2,'p_body_object','opaflib/parser.py',184),
  ('body -> <empty>','body',0,'p_body_void','opaflib/parser.py',190),
  ('pdf_brute_end -> XREF TRAILER dictionary STARTXREF EOF','pdf_brute_end',5,'p_pdf_brute_end','opaflib/parser.py',202),
]
