
# opaflib/parsetab_pdf_brute_end.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'v\xc8s\x99\xa0\x80\x10\xa9\xcbe\x07\xb2\x86\xf3\xc42'
    
_lr_action_items = {'DOUBLE_GREATER_THAN_SIGN':([5,7,9,11,12,13,14,15,16,17,19,20,21,22,26,],[-17,9,-15,-10,-6,-13,-7,-16,-8,-12,-14,-11,-9,-5,-2,]),'XREF':([0,],[1,]),'FALSE':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,11,-10,-6,-13,-7,-8,-12,11,-14,-11,-9,-5,11,-2,]),'NAME':([5,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,26,],[-17,10,-15,22,-10,-6,-13,-7,-16,-8,-12,22,-14,-11,-9,-5,22,-2,]),'HEXSTRING':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,14,-10,-6,-13,-7,-8,-12,14,-14,-11,-9,-5,14,-2,]),'DOUBLE_LESS_THAN_SIGN':([3,9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[5,-15,5,-10,-6,-13,-7,-8,-12,5,-14,-11,-9,-5,5,-2,]),'NUMBER':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,16,-10,-6,-13,-7,-8,-12,16,-14,-11,-9,-5,16,-2,]),'LEFT_SQUARE_BRACKET':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,18,-10,-6,-13,-7,-8,-12,18,-14,-11,-9,-5,18,-2,]),'STARTXREF':([4,9,],[6,-15,]),'R':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,17,-10,-6,-13,-7,-8,-12,17,-14,-11,-9,-5,17,-2,]),'TRUE':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,21,-10,-6,-13,-7,-8,-12,21,-14,-11,-9,-5,21,-2,]),'STRING':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,12,-10,-6,-13,-7,-8,-12,12,-14,-11,-9,-5,12,-2,]),'NULL':([9,10,11,12,13,14,16,17,18,19,20,21,22,23,26,],[-15,20,-10,-6,-13,-7,-8,-12,20,-14,-11,-9,-5,20,-2,]),'EOF':([6,],[8,]),'RIGHT_SQUARE_BRACKET':([9,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,],[-15,-10,-6,-13,-7,-8,-12,-4,-14,-11,-9,-5,-4,26,-3,-2,]),'TRAILER':([1,],[3,]),'$end':([2,8,],[0,-31,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object':([10,18,23,],[15,23,23,]),'dictionary':([3,10,18,23,],[4,13,13,13,]),'object_list':([18,23,],[24,25,]),'dictionary_entry_list':([5,],[7,]),'pdf_brute_end':([0,],[2,]),'array':([10,18,23,],[19,19,19,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pdf_brute_end","S'",1,None,None,None),
  ('pdf -> HEADER pdf_update_list','pdf',2,'p_pdf','opaflib/parser.py',24),
  ('array -> LEFT_SQUARE_BRACKET object_list RIGHT_SQUARE_BRACKET','array',3,'p_array','opaflib/parser.py',36),
  ('object_list -> object object_list','object_list',2,'p_object_list','opaflib/parser.py',40),
  ('object_list -> <empty>','object_list',0,'p_object_list_empty','opaflib/parser.py',44),
  ('object -> NAME','object',1,'p_object_name','opaflib/parser.py',49),
  ('object -> STRING','object',1,'p_object_string','opaflib/parser.py',53),
  ('object -> HEXSTRING','object',1,'p_object_hexstring','opaflib/parser.py',57),
  ('object -> NUMBER','object',1,'p_object_number','opaflib/parser.py',61),
  ('object -> TRUE','object',1,'p_object_true','opaflib/parser.py',65),
  ('object -> FALSE','object',1,'p_object_false','opaflib/parser.py',69),
  ('object -> NULL','object',1,'p_object_null','opaflib/parser.py',73),
  ('object -> R','object',1,'p_object_ref','opaflib/parser.py',77),
  ('object -> dictionary','object',1,'p_object_dictionary','opaflib/parser.py',82),
  ('object -> array','object',1,'p_object_array','opaflib/parser.py',86),
  ('dictionary -> DOUBLE_LESS_THAN_SIGN dictionary_entry_list DOUBLE_GREATER_THAN_SIGN','dictionary',3,'p_dictionary','opaflib/parser.py',96),
  ('dictionary_entry_list -> dictionary_entry_list NAME object','dictionary_entry_list',3,'p_dictionary_entry_list','opaflib/parser.py',100),
  ('dictionary_entry_list -> <empty>','dictionary_entry_list',0,'p_dictionary_entry_list','opaflib/parser.py',101),
  ('indirect -> indirect_object_stream','indirect',1,'p_indirect','opaflib/parser.py',119),
  ('indirect -> indirect_object','indirect',1,'p_indirect','opaflib/parser.py',120),
  ('indirect_object -> OBJ object ENDOBJ','indirect_object',3,'p_indirect_object','opaflib/parser.py',125),
  ('indirect_object_stream -> OBJ dictionary STREAM_DATA ENDOBJ','indirect_object_stream',4,'p_indirect_object_stream','opaflib/parser.py',129),
  ('xref -> XREF TRAILER dictionary','xref',3,'p_xref_common','opaflib/parser.py',146),
  ('xref -> indirect_object_stream','xref',1,'p_xref_stream','opaflib/parser.py',152),
  ('pdf_update -> body xref pdf_end','pdf_update',3,'p_pdf_update','opaflib/parser.py',157),
  ('pdf_end -> STARTXREF EOF','pdf_end',2,'p_pdf_end','opaflib/parser.py',168),
  ('pdf_update_list -> pdf_update_list pdf_update','pdf_update_list',2,'p_pdf_update_list','opaflib/parser.py',172),
  ('pdf_update_list -> pdf_update','pdf_update_list',1,'p_pdf_update_list_one','opaflib/parser.py',178),
  ('body -> body indirect_object','body',2,'p_body_object','opaflib/parser.py',183),
  ('body -> body indirect_object_stream','body',2,'p_body_object','opaflib/parser.py',184),
  ('body -> <empty>','body',0,'p_body_void','opaflib/parser.py',190),
  ('pdf_brute_end -> XREF TRAILER dictionary STARTXREF EOF','pdf_brute_end',5,'p_pdf_brute_end','opaflib/parser.py',202),
]
