
# opaflib/parsetab_object.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '4\x95\x19\x84\xdb\x06i!\xb7^\x17\xc0:{\xcb\x1e'
    
_lr_action_items = {'DOUBLE_GREATER_THAN_SIGN':([1,2,3,4,5,7,8,10,11,12,13,14,17,20,21,],[-10,-5,-13,-7,-17,-8,-12,-14,-11,-9,-6,17,-15,-2,-16,]),'FALSE':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[1,-10,-5,-13,-7,-8,-12,1,-14,-11,-9,-6,1,-15,1,-2,]),'NAME':([0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,20,21,],[2,-10,-5,-13,-7,-17,-8,-12,2,-14,-11,-9,-6,18,2,-15,2,-2,-16,]),'HEXSTRING':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[4,-10,-5,-13,-7,-8,-12,4,-14,-11,-9,-6,4,-15,4,-2,]),'DOUBLE_LESS_THAN_SIGN':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[5,-10,-5,-13,-7,-8,-12,5,-14,-11,-9,-6,5,-15,5,-2,]),'LEFT_SQUARE_BRACKET':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[9,-10,-5,-13,-7,-8,-12,9,-14,-11,-9,-6,9,-15,9,-2,]),'NUMBER':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[7,-10,-5,-13,-7,-8,-12,7,-14,-11,-9,-6,7,-15,7,-2,]),'RIGHT_SQUARE_BRACKET':([1,2,3,4,7,8,9,10,11,12,13,15,16,17,19,20,],[-10,-5,-13,-7,-8,-12,-4,-14,-11,-9,-6,-4,20,-15,-3,-2,]),'R':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[8,-10,-5,-13,-7,-8,-12,8,-14,-11,-9,-6,8,-15,8,-2,]),'NULL':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[11,-10,-5,-13,-7,-8,-12,11,-14,-11,-9,-6,11,-15,11,-2,]),'TRUE':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[12,-10,-5,-13,-7,-8,-12,12,-14,-11,-9,-6,12,-15,12,-2,]),'$end':([1,2,3,4,6,7,8,10,11,12,13,17,20,],[-10,-5,-13,-7,0,-8,-12,-14,-11,-9,-6,-15,-2,]),'STRING':([0,1,2,3,4,7,8,9,10,11,12,13,15,17,18,20,],[13,-10,-5,-13,-7,-8,-12,13,-14,-11,-9,-6,13,-15,13,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object_list':([9,15,],[16,19,]),'array':([0,9,15,18,],[10,10,10,10,]),'object':([0,9,15,18,],[6,15,15,21,]),'dictionary_entry_list':([5,],[14,]),'dictionary':([0,9,15,18,],[3,3,3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> object","S'",1,None,None,None),
  ('pdf -> HEADER pdf_update_list','pdf',2,'p_pdf','opaflib/parser.py',24),
  ('array -> LEFT_SQUARE_BRACKET object_list RIGHT_SQUARE_BRACKET','array',3,'p_array','opaflib/parser.py',36),
  ('object_list -> object object_list','object_list',2,'p_object_list','opaflib/parser.py',40),
  ('object_list -> <empty>','object_list',0,'p_object_list_empty','opaflib/parser.py',44),
  ('object -> NAME','object',1,'p_object_name','opaflib/parser.py',49),
  ('object -> STRING','object',1,'p_object_string','opaflib/parser.py',53),
  ('object -> HEXSTRING','object',1,'p_object_hexstring','opaflib/parser.py',57),
  ('object -> NUMBER','object',1,'p_object_number','opaflib/parser.py',61),
  ('object -> TRUE','object',1,'p_object_true','opaflib/parser.py',65),
  ('object -> FALSE','object',1,'p_object_false','opaflib/parser.py',69),
  ('object -> NULL','object',1,'p_object_null','opaflib/parser.py',73),
  ('object -> R','object',1,'p_object_ref','opaflib/parser.py',77),
  ('object -> dictionary','object',1,'p_object_dictionary','opaflib/parser.py',82),
  ('object -> array','object',1,'p_object_array','opaflib/parser.py',86),
  ('dictionary -> DOUBLE_LESS_THAN_SIGN dictionary_entry_list DOUBLE_GREATER_THAN_SIGN','dictionary',3,'p_dictionary','opaflib/parser.py',96),
  ('dictionary_entry_list -> dictionary_entry_list NAME object','dictionary_entry_list',3,'p_dictionary_entry_list','opaflib/parser.py',100),
  ('dictionary_entry_list -> <empty>','dictionary_entry_list',0,'p_dictionary_entry_list','opaflib/parser.py',101),
  ('indirect -> indirect_object_stream','indirect',1,'p_indirect','opaflib/parser.py',119),
  ('indirect -> indirect_object','indirect',1,'p_indirect','opaflib/parser.py',120),
  ('indirect_object -> OBJ object ENDOBJ','indirect_object',3,'p_indirect_object','opaflib/parser.py',125),
  ('indirect_object_stream -> OBJ dictionary STREAM_DATA ENDOBJ','indirect_object_stream',4,'p_indirect_object_stream','opaflib/parser.py',129),
  ('xref -> XREF TRAILER dictionary','xref',3,'p_xref_common','opaflib/parser.py',146),
  ('xref -> indirect_object_stream','xref',1,'p_xref_stream','opaflib/parser.py',152),
  ('pdf_update -> body xref pdf_end','pdf_update',3,'p_pdf_update','opaflib/parser.py',157),
  ('pdf_end -> STARTXREF EOF','pdf_end',2,'p_pdf_end','opaflib/parser.py',168),
  ('pdf_update_list -> pdf_update_list pdf_update','pdf_update_list',2,'p_pdf_update_list','opaflib/parser.py',172),
  ('pdf_update_list -> pdf_update','pdf_update_list',1,'p_pdf_update_list_one','opaflib/parser.py',178),
  ('body -> body indirect_object','body',2,'p_body_object','opaflib/parser.py',183),
  ('body -> body indirect_object_stream','body',2,'p_body_object','opaflib/parser.py',184),
  ('body -> <empty>','body',0,'p_body_void','opaflib/parser.py',190),
  ('pdf_brute_end -> XREF TRAILER dictionary STARTXREF EOF','pdf_brute_end',5,'p_pdf_brute_end','opaflib/parser.py',202),
]
