
# opaflib/parsetab_indirect.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'p\x19)\xc3\x03\x87\x989n-J\x00/\xe7yg'
    
_lr_action_items = {'DOUBLE_GREATER_THAN_SIGN':([6,8,9,11,12,13,14,15,16,17,19,22,25,27,29,],[-5,-7,-17,-8,-12,-10,-14,-11,-9,-6,-13,27,-2,-15,-16,]),'FALSE':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[13,13,-5,-7,-8,-12,-10,-14,-11,-9,-6,13,-13,-2,-15,13,]),'NAME':([1,5,6,8,9,11,12,13,14,15,16,17,18,19,22,25,27,28,29,],[6,6,-5,-7,-17,-8,-12,-10,-14,-11,-9,-6,6,-13,28,-2,-15,6,-16,]),'ENDOBJ':([6,7,8,10,11,12,13,14,15,16,17,21,25,27,],[-5,-13,-7,23,-8,-12,-10,-14,-11,-9,-6,26,-2,-15,]),'HEXSTRING':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[8,8,-5,-7,-8,-12,-10,-14,-11,-9,-6,8,-13,-2,-15,8,]),'DOUBLE_LESS_THAN_SIGN':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[9,9,-5,-7,-8,-12,-10,-14,-11,-9,-6,9,-13,-2,-15,9,]),'NUMBER':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[11,11,-5,-7,-8,-12,-10,-14,-11,-9,-6,11,-13,-2,-15,11,]),'LEFT_SQUARE_BRACKET':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[5,5,-5,-7,-8,-12,-10,-14,-11,-9,-6,5,-13,-2,-15,5,]),'RIGHT_SQUARE_BRACKET':([5,6,8,11,12,13,14,15,16,17,18,19,20,24,25,27,],[-4,-5,-7,-8,-12,-10,-14,-11,-9,-6,-4,-13,25,-3,-2,-15,]),'R':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[12,12,-5,-7,-8,-12,-10,-14,-11,-9,-6,12,-13,-2,-15,12,]),'STREAM_DATA':([7,27,],[21,-15,]),'OBJ':([0,],[1,]),'NULL':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[15,15,-5,-7,-8,-12,-10,-14,-11,-9,-6,15,-13,-2,-15,15,]),'TRUE':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[16,16,-5,-7,-8,-12,-10,-14,-11,-9,-6,16,-13,-2,-15,16,]),'$end':([2,3,4,23,26,],[-19,-18,0,-20,-21,]),'STRING':([1,5,6,8,11,12,13,14,15,16,17,18,19,25,27,28,],[17,17,-5,-7,-8,-12,-10,-14,-11,-9,-6,17,-13,-2,-15,17,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object_list':([5,18,],[20,24,]),'dictionary':([1,5,18,28,],[7,19,19,19,]),'object':([1,5,18,28,],[10,18,18,29,]),'dictionary_entry_list':([9,],[22,]),'indirect_object':([0,],[2,]),'indirect_object_stream':([0,],[3,]),'indirect':([0,],[4,]),'array':([1,5,18,28,],[14,14,14,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> indirect","S'",1,None,None,None),
  ('pdf -> HEADER pdf_update_list','pdf',2,'p_pdf','opaflib/parser.py',24),
  ('array -> LEFT_SQUARE_BRACKET object_list RIGHT_SQUARE_BRACKET','array',3,'p_array','opaflib/parser.py',36),
  ('object_list -> object object_list','object_list',2,'p_object_list','opaflib/parser.py',40),
  ('object_list -> <empty>','object_list',0,'p_object_list_empty','opaflib/parser.py',44),
  ('object -> NAME','object',1,'p_object_name','opaflib/parser.py',49),
  ('object -> STRING','object',1,'p_object_string','opaflib/parser.py',53),
  ('object -> HEXSTRING','object',1,'p_object_hexstring','opaflib/parser.py',57),
  ('object -> NUMBER','object',1,'p_object_number','opaflib/parser.py',61),
  ('object -> TRUE','object',1,'p_object_true','opaflib/parser.py',65),
  ('object -> FALSE','object',1,'p_object_false','opaflib/parser.py',69),
  ('object -> NULL','object',1,'p_object_null','opaflib/parser.py',73),
  ('object -> R','object',1,'p_object_ref','opaflib/parser.py',77),
  ('object -> dictionary','object',1,'p_object_dictionary','opaflib/parser.py',82),
  ('object -> array','object',1,'p_object_array','opaflib/parser.py',86),
  ('dictionary -> DOUBLE_LESS_THAN_SIGN dictionary_entry_list DOUBLE_GREATER_THAN_SIGN','dictionary',3,'p_dictionary','opaflib/parser.py',96),
  ('dictionary_entry_list -> dictionary_entry_list NAME object','dictionary_entry_list',3,'p_dictionary_entry_list','opaflib/parser.py',100),
  ('dictionary_entry_list -> <empty>','dictionary_entry_list',0,'p_dictionary_entry_list','opaflib/parser.py',101),
  ('indirect -> indirect_object_stream','indirect',1,'p_indirect','opaflib/parser.py',119),
  ('indirect -> indirect_object','indirect',1,'p_indirect','opaflib/parser.py',120),
  ('indirect_object -> OBJ object ENDOBJ','indirect_object',3,'p_indirect_object','opaflib/parser.py',125),
  ('indirect_object_stream -> OBJ dictionary STREAM_DATA ENDOBJ','indirect_object_stream',4,'p_indirect_object_stream','opaflib/parser.py',129),
  ('xref -> XREF TRAILER dictionary','xref',3,'p_xref_common','opaflib/parser.py',146),
  ('xref -> indirect_object_stream','xref',1,'p_xref_stream','opaflib/parser.py',152),
  ('pdf_update -> body xref pdf_end','pdf_update',3,'p_pdf_update','opaflib/parser.py',157),
  ('pdf_end -> STARTXREF EOF','pdf_end',2,'p_pdf_end','opaflib/parser.py',168),
  ('pdf_update_list -> pdf_update_list pdf_update','pdf_update_list',2,'p_pdf_update_list','opaflib/parser.py',172),
  ('pdf_update_list -> pdf_update','pdf_update_list',1,'p_pdf_update_list_one','opaflib/parser.py',178),
  ('body -> body indirect_object','body',2,'p_body_object','opaflib/parser.py',183),
  ('body -> body indirect_object_stream','body',2,'p_body_object','opaflib/parser.py',184),
  ('body -> <empty>','body',0,'p_body_void','opaflib/parser.py',190),
  ('pdf_brute_end -> XREF TRAILER dictionary STARTXREF EOF','pdf_brute_end',5,'p_pdf_brute_end','opaflib/parser.py',202),
]
